### ISSUE TITLE
compilation problems

### ISSUE THREAD

**Issue by leonardpitzu** [sticilface/ESPmanager#10]
problem #1 - DEBUG cauzez problems with arduino.h
problem #2 - after fixing the above issue ESPmanager.cpp:202:10: error: no matching function for call to 'ArduinoOTAClass::onStart(ESPmanager::begin()::__lambda0)'
         });

i use latest versions of arduino ide/compiler/libraries + esp8266 sdk/arduino core

**Comment by sticilface** [comment]
can u post the full error code?   bit weird as I'm not having any problems compiling with arduino

**Comment by leonardpitzu** [comment]
it was your sample which was not working and i posted the code after extensive testing. apparently not extensive enough though as an uninstall, reboot and then fresh install of arduino + esp8266 sdk/compiler/arduino libs resolved the issue. thanks for your quick reaction and sorry for the false report.

**Comment by sticilface** [comment]
no problem.
