### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by fireboy1919** [sticilface/ESPmanager#21]
It refers to "settings.portal" which I believe has been renamed to "settings.enablePortal."

At any rate, the example as its presented doesn't actually work.

**Comment by sticilface** [comment]
I'll take a look. I might have renamed the function by accident.

**Comment by sticilface** [comment]
Could you paste the error?

I assume you are referring to this line https://github.com/sticilface/ESPmanager/blob/master/examples/ESPmanager-example/ESPmanager-example.ino#L60

which is still a function
https://github.com/sticilface/ESPmanager/blob/master/src/ESPmanager.h#L114

so im not sure why it doesn't work
