### ISSUE TITLE
no member named 'getSketchMD5'

### ISSUE THREAD

**Issue by ghost** [sticilface/ESPmanager#22]
Compile error: 
-----------------------------
C:\...\portable\sketchbook\libraries\ESPmanager\src\ESPmanager.cpp: In member function 'String ESPmanager::getSketchMD5()':

C:\...\portable\sketchbook\libraries\ESPmanager\src\ESPmanager.cpp:981:16: error: 'class EspClass' has no member named 'getSketchMD5'

     return ESP.getSketchMD5();
-----------------------------
Arduino IDE 1.8.1
esp8266 : 2.3.0-rc2

String ESPmanager::getSketchMD5()
{
    return ESP.getSketchMD5();
}
to

String ESPmanager::getSketchMD5()
{
    return "1";//ESP.getSketchMD5();
}

ITS NOT A FIX !!! Only to get it compiling for a first try... 

peter

**Comment by sticilface** [comment]
My guess is that your version of the arduino esp8266 is quite outdated. This function has been around for quite a while. 

https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Esp.h#L136. Try updating. This may also fix the crash on network scanning.

**Comment by ghost** [comment]
Hmm, not in the stable version of code !? Newer than that (git clone) is not available via the Boardmanager of the Arduino IDE...

**Comment by sticilface** [comment]
I would recommend following the instructions here:
https://github.com/esp8266/Arduino#using-git-version

for how to install the git version.  The stable and staging versions are nearly 1 year out of date now!
