### ISSUE TITLE
ajax-loader.gif

### ISSUE THREAD

**Issue by ghost** [sticilface/ESPmanager#24]
The ajax-loader.gif is not shown during setup (waiting for launch button).

Andriod / Chrome
Windows / FF

direct opened in the browser 
http://192.168.1.190/espman/ajax-loader.gif

I get: The image "http://http://192.168.1.190/espman/ajax-loader.gif" cannot be displayed because it contains errors.

peter

**Comment by sticilface** [comment]
that looks like the url is wrong. with two http://...

I've tried the URL on my devices and it works fine. 

<img width="712" alt="screenshot 2017-04-27 10 55 06" src="https://cloud.githubusercontent.com/assets/10061736/25478176/06c61590-2b38-11e7-8867-6e933fc81aec.png">

so not sure...  try re imaging the SPIFFS maybe it is corrupt

**Comment by sticilface** [comment]
fixed with a redirect in develop
