### ISSUE TITLE
Captive portal in AP mode

### ISSUE THREAD

**Issue by probonopd** [sticilface/ESPmanager#9]
The instructions say "Now visit http://X.X.X.X/espman/ and it should work". This is cumbersome and difficult to communicate. It would be better if in AP mode ESPmanager would answer all nameserver requests with its own IP address. This way we could tell users "connect to the AP and then visit any URL, you will be directed automatically".

The [DNSServer library](https://github.com/esp8266/Arduino/tree/master/libraries/DNSServer) has the needed "captive portal" functionality.

Tutorial:
https://www.hackster.io/rayburne/esp8266-captive-portal-5798ff

**Comment by sticilface** [comment]
I've implemented this, and will release it shortly.  I'm also working on a  set up wizard to make it all pretty easy to configure!
